# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: local
      hooks:
          - id: nbdev_docs
            name: nbdev_docs
            entry: nbdev_docs
            language: system
            pass_filenames: false
    - repo: local
      hooks:
          - id: nbdev_readme
            name: nbdev_readme
            entry: nbdev_readme
            language: system
            pass_filenames: false
    - repo: local
      hooks:
          - id: nbdev_export
            name: nbdev_export
            entry: nbdev_export
            language: system
            pass_filenames: false
