# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ad_complete.ipynb.

# %% auto 0
__all__ = ['df']

# %% ../nbs/03_ad_complete.ipynb 3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime as dt
from .concepts import get_window
from scipy import signal
import os
import math
import torch

# %% ../nbs/03_ad_complete.ipynb 4
from torch import nn
import torch.nn.functional as F
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_auc_score, accuracy_score


# %% ../nbs/03_ad_complete.ipynb 5
from .vae import VAE, Encoder, Decoder, StochasticSampler
from fastcore.xtras import noop


# %% ../nbs/03_ad_complete.ipynb 10
df = pd.DataFrame(data["test"], index=data["t_test"], columns=["value"])
df.head(2)
