# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_lstm.ipynb.

# %% auto 0
__all__ = ['BASEDIR', 'MODELDIR', 'TSLSTMDataset', 'LSTMModel']

# %% ../nbs/02_lstm.ipynb 3
from dotenv import load_dotenv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime as dt
from .concepts import get_window
from scipy import signal
import os
import math
import torch

# %% ../nbs/02_lstm.ipynb 6
load_dotenv()

BASEDIR = os.getenv("BASEDIR")
MODELDIR = os.getenv("MODELDIR")

# %% ../nbs/02_lstm.ipynb 8
from torch import nn
import torch.nn.functional as F
import torch
from torch.utils.data import Dataset, DataLoader

# %% ../nbs/02_lstm.ipynb 9
from .vae import VAE, Encoder, Decoder, StochasticSampler
from fastcore.xtras import noop

# %% ../nbs/02_lstm.ipynb 38
class TSLSTMDataset(Dataset):
    def __init__(
        self,
        embeddings,  # full dataset (not separated as we need to index the next window)
        indices,
        # window_size=48,
        # latent_dim=32,
        # n_features=1,
        # n_prev_windows=1,
        mean=0,
        std=1,
    ):
        self.embeddings = embeddings
        self.indices = indices  # (idx, idx+1) pairs)
        self.mean = mean
        self.std = std
        # self.n_prev_windows = n_prev_windows
        # self.window_size = window_size
        # self.n_features = n_features
        # self.latent_dim = latent_dim

    def __getitem__(self, idx):
        xidx, yidx = self.indices[idx]
        # per-window statistics could be anopter way to do this.
        x_emb = (self.embeddings[xidx]["subset"] - self.mean) / self.std
        # target is the next point in x_emb, but need the first point of y_emb aslo
        emb_next = (self.embeddings[yidx]["subset"][0] - self.mean) / self.std
        emb_next = emb_next.unsqueeze(1)
        # create offsetted y_emb
        y_emb = torch.concat([x_emb[1:], emb_next])
        return x_emb, y_emb  # latent_dim, seq_len

    def __len__(self):
        return len(self.indices)

# %% ../nbs/02_lstm.ipynb 50
class LSTMModel(nn.Module):
    def __init__(
        self, input_size=32, hidden_size=128, output_size=32, activation=F.mish
    ):
        super(LSTMModel, self).__init__()
        self.isz = input_size
        self.hsz = hidden_size
        self.osz = output_size
        self.lstm_input = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,  # output_size,
            batch_first=True,
            # bidirectional=True,
            num_layers=2,
        )
        self.lstm_hidden = nn.LSTM(
            input_size=hidden_size,  # output_size,
            hidden_size=hidden_size,
            batch_first=True,
            # bidirectional=True,
            num_layers=1,
        )
        self.lstm_output = nn.LSTM(
            input_size=hidden_size,
            hidden_size=output_size,
            num_layers=1,
            batch_first=True,
        )
        self.ln1 = nn.LayerNorm(hidden_size)
        self.ln2 = nn.LayerNorm(hidden_size)
        self.activation = activation
        self.dropout = nn.Dropout(0.5)
        self._init_lstm_weights()

    def forward(self, x):
        # x has shape bs, emb_dim, seq_len (emb_dim=latent_dim, seq_len=1)
        x = x.permute(0, 2, 1)  # bs, seq_len, emb_dim
        # LSTM1
        lstm_out1, _ = self.lstm_input(x)
        lstm_out1 = self.dropout(self.activation(self.ln1(lstm_out1)))
        # print(lstm_out1.shape)
        # LSTM2
        lstm_out2, _ = self.lstm_hidden(lstm_out1)
        lstm_out2 = self.dropout(self.activation(self.ln2(lstm_out2)))
        # LSTM3
        lstm_out3, _ = self.lstm_output(lstm_out2)
        return lstm_out3.permute(0, 2, 1)  # bs, output_size, seq_len

    def _init_lstm_weights(self):
        for layer in [self.lstm_input, self.lstm_hidden, self.lstm_output]:
            for name, param in layer.named_parameters():
                if "weight" in name:
                    nn.init.xavier_normal_(param)
                elif "bias" in name:
                    nn.init.constant_(param, 0.0)

# %% ../nbs/02_lstm.ipynb 57
from fastcore.xtras import partial
